### PR TITLE
Add CI tests for Python 3.11

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR test jobs for Python 3.11.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
The `pip`-based tests need h5py wheels for Python 3.11.

**Comment by duncanmmacleod** [comment]
This is blocked by https://github.com/duncanmmacleod/pip2conda/issues/19.

**Review by hoyc1 — APPROVED** [review]
LGTM!

**Review by areeda — APPROVED** [review]
LGTM

**Pull request merged**
