### PR TITLE
Long dur specgram - fixes merge conflics, labels with wrong time, bug in building docs and uses warn not pring

### LINKED ISSUE #63: cli labels with wrong UTC time
CLI program is missing a scale kwarg when creating a time object from GPS times so the labels are off by 35 seconds.

### LINKED ISSUE #68: cli: example fails on 58a68a
On the current `HEAD` of the GWpy repository, the CLI example `cli-spg-01.png` fails to build as follows:

```
$ make ../build/sphinx/cli_examples/cli-spg-01.png
cli-spg-01
Traceback (most recent call last):
  File "../bin/gwpy-plot", line 118, in <module>
    result_code = prod.makePlot(args)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/cli/cliproduct.py", line 797, in makePlot
    self.gen_plot(args)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/cli/spectrogram.py", line 94, in gen_plot
    snr_nfft = self.dur / (secpfft * stride)
NameError: global name 'stride' is not defined
make: *** [../build/sphinx/cli_examples/cli-spg-01.png] Error 1
```

@areeda, can you take a look?

### PR DESCRIPTION
**Pull request by areeda**
Fixes #68 Failure in building documentation examles
Fixes #67 The revert on previous pull
Fixes #65 Merge conflict 
Fixes #63 Labels with wrong UTC time

All were minor changes
Main issue is to choose between the two Spectrogram implementations.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@areeda, please edit the title of this PR to give it a more descriptive name.

Also, I'm wondering if the best solution might be to use a `warning.warn` call instead of a simple `print` statement to tell the user that the coherence will not be calculated?

**Comment by areeda** [comment]
Title edited and I'll look up warning.warn

**Comment by duncanmmacleod** [comment]
I've built the documentation and everything works. So I'm happy to merge as soon as you've had a chance to replace that `print` statement with a `warnings.warn` call.

**Comment by areeda** [comment]
Now uses warnings.warn and passes pep8

**Pull request merged**
