### PR TITLE
Rebuild of Array and sub-classes

### LINKED ISSUE #66: cli: Setting only one frequency axis limit causes Quantity vs Float conflict
Bitten once again by this. I guess floats can't walk like a Quantity and Quantities can't walk like a float.

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR introduces a complete re-build of the `Array` class and all sub-classes, including `TimeSeries`, `Spectrum`, and `Spectrogram`. The changes are (at least) as follows:

- `Array` now inherits from `astropy.units.Quantity` rather than from `numpy.ndarray`,
    - all unit handing is now much easier, with most of it handled directly by `Quantity`,
    - the `unit` property cannot be set for an array that already has a unit, a notice has been added to the exception message to ask the user to use the `Array.to()` method, which properly converts between units,
    - the `data` property has been removed in favour of the `Quantity.value` property. `data` was a bad choice to begin with as it overrode a `numpy.ndarray` property,
- `Array2D` now inherits from `Series`,
- the `times` and `frequencies` indexes of the `TimeSeries`, `Spectrum`, and `Spectrogram` classes are now simply `Quantity` arrays, rather than `Series`, this means that they don't have the extra metadata they used to (`epoch`, `channel`, `name`), 

All downstream codes have been modified to handle the new base classes. 

This fixes #66.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@areeda: can you review this PR with respect to the `gwpy/cli/` file changes and let me know if everything is ok? I think the majority of the changes are `.data` -> `.value`, with a few related to the fact that `.times` now doesn't have an `epoch`.

**Comment by maxisi** [comment]
Hello, will this affect gwsumm functionality?

On Wednesday, April 15, 2015, Duncan Macleod <notifications@github.com>
wrote:

> This PR introduces a complete re-build of the Array class and all
> sub-classes, including TimeSeries, Spectrum, and Spectrogram. The changes
> are (at least) as follows:
>
>    - Array now inherits from astropy.units.Quantity rather than from
>    numpy.ndarray,
>       - all unit handing is now much easier, with most of it handled
>       directly by Quantity,
>       - the unit property cannot be set for an array that already has a
>       unit, a notice has been added to the exception message to ask the user to
>       use the Array.to() method, which properly converts between units,
>       - the data property has been removed in favour of the Quantity.value
>       property. data was a bad choice to begin with as it overrode a
>       numpy.ndarray property,
>     - Array2D now inherits from Series,
>    - the times and frequencies indexes of the TimeSeries, Spectrum, and
>    Spectrogram classes are now simply Quantity arrays, rather than Series,
>    this means that they don't have the extra metadata they used to (epoch,
>    channel, name),
>
> All downstream codes have been modified to handle the new base classes.
>
> This fixes #66 <https://github.com/gwpy/gwpy/issues/66>.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/gwpy/gwpy/pull/78
> Commit Summary
>
>    - gwpy.data: MAJOR REWORKING
>    - gwpy.tests.array: new Array/Array2D/Series tests
>    - gwpy.tests.astro: update .data -> .value
>    - TimeSeries.__array_wrap__: remove unnecessary line
>    - Array: override dumps and tostring to enable pickling
>    - tests: added TimeSeries pickle test
>    - TimeSeries.fetch: remove print statements
>    - Array._wrap_function: use Quantity ufunc wrapper
>    - Array2D.__array_wrap__: fix bug in context passing
>    - Spectrogram.ratio: greatly simplified method
>    - cli.coherence: don't use TimeSeries.times.epoch
>    - xindex/yindex: don't use dtype, causes precision errors
>    - cli.spectrum: fixed Quantity vs float mismatch
>    - TimeSeries: remove buggy unit settings
>    - spectrogram/coherence: fix bug in stride
>    - Array.unit: improved default unit settings
>    - Merge branch 'master' into array_simplification
>
> File Changes
>
>    - *M* gwpy/astro/range.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-0> (20)
>    - *M* gwpy/cli/coherence.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-1> (14)
>    - *M* gwpy/cli/coherencegram.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-2> (6)
>    - *M* gwpy/cli/spectrogram.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-3> (8)
>    - *M* gwpy/cli/spectrum.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-4> (24)
>    - *M* gwpy/cli/timeseries.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-5> (16)
>    - *M* gwpy/data/array.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-6> (405)
>    - *M* gwpy/data/array2d.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-7> (360)
>    - *M* gwpy/data/series.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-8> (379)
>    - *M* gwpy/io/ascii.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-9> (6)
>    - *M* gwpy/plotter/filter.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-10> (8)
>    - *M* gwpy/plotter/histogram.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-11> (2)
>    - *M* gwpy/plotter/html.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-12> (2)
>    - *M* gwpy/plotter/spectrum.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-13> (33)
>    - *M* gwpy/plotter/timeseries.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-14> (29)
>    - *M* gwpy/spectrogram/coherence.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-15> (7)
>    - *M* gwpy/spectrogram/core.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-16> (116)
>    - *M* gwpy/spectrogram/spectrogram.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-17> (2)
>    - *M* gwpy/spectrum/core.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-18> (33)
>    - *M* gwpy/spectrum/hist.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-19> (53)
>    - *M* gwpy/spectrum/psd.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-20> (2)
>    - *M* gwpy/spectrum/scipy_.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-21> (16)
>    - *A* gwpy/tests/array.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-22> (123)
>    - *M* gwpy/tests/astro.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-23> (4)
>    - *M* gwpy/tests/timeseries.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-24> (10)
>    - *M* gwpy/timeseries/common.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-25> (8)
>    - *M* gwpy/timeseries/core.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-26> (120)
>    - *M* gwpy/timeseries/io/gwf/framecpp.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-27> (4)
>    - *M* gwpy/timeseries/statevector.py
>    <https://github.com/gwpy/gwpy/pull/78/files#diff-28> (44)
>
> Patch Links:
>
>    - https://github.com/gwpy/gwpy/pull/78.patch
>    - https://github.com/gwpy/gwpy/pull/78.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gwpy/gwpy/pull/78>.
>


-- 
California Institute of Technology
LIGO Laboratory, MS 100-36
Pasadena, CA 91125

**Comment by duncanmmacleod** [comment]
@maxisi, I am testing `gwsumm` now, and it looks like one or two minor edits will be needed, but nothing major. I will try and modify `gwsumm` so it works wether you update `gwpy` or not.

**Comment by duncanmmacleod** [comment]
I have pushed gwpy/gwsumm@25bf54e9da9f35902be12507b77fdfe521290ee8 to the only compatibility issue I found. This change is backwards compatible (or at least it should be).

**Comment by maxisi** [comment]
Great, I'll sync my fork and let you know if any problems arise.

**Pull request merged**
