### PR TITLE
Version for gwpy release

### LINKED ISSUE #41: gwpy-plot can't display simple GPS times on time axis
The `gwpy-plot` command-line interface doesn't expose any time-axis scale options to the user, meaning they can't choose between the (default) human-readable 'Time (some unit) from epoch', and just displaying the GPS times.

I'm not sure if GWpy can actually display just GPS times, without matplotlib imposing an offset, but this should be workable pretty quickly.

### PR DESCRIPTION
**Pull request by areeda**
latest (and last change) has the option for GPS labels for time axis and removes the word "log" from Spectrogram colorbar label.

When this is merged we are ready to release ldvw.

2 minor pep8 issues fixed.

This fixes #41.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@areeda: I trust that you have completed all the necessary testing. I'll wait until the Travis build completes with success, and I can build the documentation on py26 and py27, then I will merge.

**Comment by duncanmmacleod** [comment]
So my sphinx build doesn't complete on py26 due to failing cli examples, however, I am confident that these bugs were not introduced in this PR, so I'll let them pass. I have fixes prepared for these in another branch that I will move into a PR before the LDVW release.

**Comment by areeda** [comment]
I've been building documentation with 26 and the only issue is that I have to comment out that ...api thingy in the conf.py.  I'm not sure what it does but it's been an issue since we first forked.

**Comment by duncanmmacleod** [comment]
I think this is an astropy/matplotlib issue, rather than just a python
version issue, I have created PR #45 to fix this issue.

On 9 March 2015 at 12:53, areeda <notifications@github.com> wrote:

> I've been building documentation with 26 and the only issue is that I have
> to comment out that ...api thingy in the conf.py. I'm not sure what it does
> but it's been an issue since we first forked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gwpy/gwpy/pull/43#issuecomment-77906098>.
>



-- 
Duncan Macleod
duncanmmacleod@gmail.com

**Comment by duncanmmacleod** [comment]
@areeda, if this PR will fix #41, please note that in the description (first comment) for this PR. That way the relevant issue will get automatically closed when the PR is merged.

**Comment by areeda** [comment]
This should be everything for the release.

**Pull request merged**
