### PR TITLE
Fix Docs of class BodePlot

### LINKED ISSUE #1332: Bode Plot (`db` argument not working)
Dear Duncan, 

I have been trying to use the BodePlot function with the option to show the magnitude of the filter in normal units, i.e.: db=False. 
The version of gwpy that I'm using is 2.0.2
````python
hp = filter_design.highpass(12, resample_rate, fstop=6, gpass=2, gstop=30,type='fir')
plot = BodePlot(hp, sample_rate=4096,db=False)
plt.xlim(20,1000)
plot.show()
````
However, I am getting the following error. 

````python
AttributeError: 'Line2D' object has no property 'db'
````
Thank you and best regards, 
Alba Romero.

### PR DESCRIPTION
**Pull request by aromerorodriguez**
Fixed the typo where argument `dB` was written as `db`, which would mislead the user when using this class. This pull request is in reference to #1332.

EDIT (@duncanmmacleod): closes #1332.

### CODE REVIEW

**Review by hoyc1 — COMMENTED** [review]
This looks good to me!

**Review by hoyc1 — APPROVED** [review]

**Comment by duncanmmacleod** [comment]
@aromerorodriguez, sorry for letting this linger for so long - the test failures have been fixed upstream, can you please rebase your pull request against the master branch?

**Comment by duncanmmacleod** [comment]
@aromerorodriguez, please rebase this PR.

**Comment by aromerorodriguez** [comment]
Hi @duncanmmacleod ,

I have just rebased the PR.
Let me know if there's anything else I should do. 

Thank you and best, 
Alba.

**Comment by duncanmmacleod** [comment]
Thanks @aromerorodriguez!

**Pull request merged**
