### PR TITLE
Silence LAL LIGOTimeGPS warnings when parsing a cache

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR silences annoying LAL debug warnings related to attempting to parse a cache as either Virgo-style FFL or LAL format.

The new contextmanager function may be useful more generally, but I haven't found a use case for that _right now_ so left the implementation in the current overly-specific place.

Closes #1681.

### CODE REVIEW

**Comment by johnveitch** [comment]
@duncanmmacleod I can confirm this squashes the irrelevant warning messages in #1681

**Comment by duncanmmacleod** [comment]
@eagoetz, I think you might be familiar with LAL's annoying debug messages, can you please review this?

**Comment by johnveitch** [comment]
Just a ping to get this merged... 
@eagoetz @duncanmmacleod

**Comment by johnveitch** [comment]
@duncanmmacleod @eagoetz Can we get this released? It's been tested and sitting here for months!

**Review by eagoetz — APPROVED** [review]
It looks reasonable to me, though I will say that I'm not familiar enough with how this should work as to why there needs to be some wrapping of the actual code doing the silencing in `yield` statements. I guess that is how it works and you've tested the warnings are silenced properly, so I will approve

**Comment by eagoetz** [comment]
@duncanmmacleod Just wanted to confirm that the failing CI tests are not a problem...?

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod Just wanted to confirm that the failing CI tests are not a problem...?

The failures should be resolved by #1723.

**Comment by johnveitch** [comment]
Thank you!

**Pull request merged**
