### PR TITLE
fix Quantity resize in Series.append

### PR DESCRIPTION
**Pull request by stefco**
described in issue #758, https://github.com/gwpy/gwpy/issues/758

When trying to append to a `Series` instance that already has _xindex initialized with an `astropy.units.Quantity` value, an error is thrown due to the fact that `Quantity` only owns a view to its own data and cannot therefore be resized.

Fix this by trying to copy the underlying numpy array in `quantity.value`, resizing that copy, and then creating a new `Quantity` instance with the resized array and the original `quantity.unit`.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@stefco, I finally found the time to look into this, and I think you're misunderstanding the issue. The problem is reference counting, not data ownership - the first `try/except` clause catches that. I can fix the issue with the following patch:

```diff
diff --git a/gwpy/types/series.py b/gwpy/types/series.py
index b9a5f6ff..a190471f 100644
--- a/gwpy/types/series.py
+++ b/gwpy/types/series.py
@@ -685,8 +685,8 @@ class Series(Array):
                     self.xindex.resize((s[0],), refcheck=False)
                 except ValueError as exc:
                     if 'cannot resize' in str(exc):
-                        self.xindex = self.xindex.copy()
-                        self.xindex.resize((s[0],))
+                        self._xindex = self.xindex.copy()
+                        self._xindex.resize((s[0],))
                     else:
                         raise
             else:
```

Using the direct attribute reference `_xindex` rather than the property reference `xindex` gets directly to the new object (the copied array) without creating another reference to it in the property methods.

Can you try this out and if it works simplify your PR to implement it?

**Comment by stefco** [comment]
Yeah, i’ll try that out! Thanks!

**Comment by duncanmmacleod** [comment]
Bump @stefco

**Comment by duncanmmacleod** [comment]
This hasn't seen attention in too long, I'm closing. Please reopen if the changes are still relevant.

**Pull request closed without merging**
