### PR TITLE
Remove unused import

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR removes an unused import that somehow slipped past the linter.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
This is bogus, somehow.

**Comment by alurban** [comment]
@duncanmmacleod, do you mean the PR itself was bogus or the result of the linter?

**Comment by duncanmmacleod** [comment]
The PR, I got tangled in some branches (git pun) and had some trouble working my way out.

**Comment by alurban** [comment]
Aha! Happens to the best of us, I just wanted to make sure it wasn't a security issue.

**Comment by duncanmmacleod** [comment]
Nope, it was actually me - the posted commit has my GPG signature on it, which is as good security as we get.

**Pull request closed without merging**
