### PR TITLE
Require lscsoft-glue >= 1.60.0

### LINKED ISSUE #928: Update lscsoft-glue dependence to 1.60+
The `glue.segments` module is also being deprecated in favor of `ligo.segments`.

### PR DESCRIPTION
**Pull request by alurban**
This fixes #928.

cc @duncanmmacleod

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@alurban, thanks for this, unfortunately `lscsoft-glue-1.60.0` is not available from pypi.python.org yet, I have requested this from @rpfisher. Once that is available I can rerun all of the CI.

**Comment by alurban** [comment]
thanks @duncanmmacleod, sounds like this will affect gwdetchar/gwdetchar#167 and gwdetchar/hveto#89 as well.

**Comment by alurban** [comment]
@duncanmmacleod, `lscsoft-glue-1.60.0` has been uploaded to PyPI, so this should now be good to roll.

**Comment by duncanmmacleod** [comment]
@alurban, given that `gwpy` has no dependence upon `glue.segments` why is this change necessary?

**Comment by alurban** [comment]
@duncanmmacleod, you are definitely a much better arbiter of whether it's necessary than I am, I was just hunting down any reference to `lscsoft-glue` in repositories with DetChar tools and changing them with reckless abandon. I'm happy enough to have this PR closed without merging if GWPy doesn't need it

**Comment by duncanmmacleod** [comment]
@alurban, in that case I suggest closing this ticket without merging, but we can come back to it at a later date if we need to.

**Pull request closed without merging**
