### PR TITLE
Q-transform

### PR DESCRIPTION
**Pull request by areeda**
Added Q-xform  product and removed limits on # of channels

### CODE REVIEW

**Comment by areeda** [comment]
I've resolved the merge conflicts but there seems to be some file corruption.  I need to go through my test suite.
Please hold off on the merge request

**Comment by areeda** [comment]
OK we have tested the changes and now I believe we're ready.

**Comment by duncanmmacleod** [comment]
@areeda, fd082ce seems to have replaced some symlinks with copies of files, presuming this wasn't deliberate, it would be nice to undo this.

**Comment by areeda** [comment]
I'm not sure how this happened let alone how to undo it.
Any suggestion to shorten my search?

**Comment by duncanmmacleod** [comment]
@areeda, my recommendation would be to `git rebase -i` to reorder the commits to put fd082ce on top, then `git reset --head HEAD^` to delete it from the history.

However, given that this PR now has 76 commits in it, I am really tempted to get you on the phone and restart this PR fresh on a feature branch, with only the commits that are really functional.

**Pull request closed without merging**
