### PR TITLE
Fix flake8 configuration and then fix lint

### PR DESCRIPTION
**Pull request by duncanmmacleod**
For some reason the flake8 builds haven't been showing much lint. This PR fixes the configuration, then fixes all of the lint hiding under the sofa.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@alurban, @areeda, @scottcoughlin2014, please review changes to those files you should feel ownership of - there should be _no_ functional changes at all, just pedantic formatting. This is best evidences by the fact that there are almost no changes of any kind in test modules.

**Review by alurban — APPROVED** [review]
Everything looks good to me @duncanmmacleod, thanks for doing all this

**Comment by duncanmmacleod** [comment]
Ping @areeda, @scottcoughlin2014, please review this.

**Review by scottcoughlin2014 — APPROVED** [review]
@duncanmmacleod looks good! Thank you!

**Comment by duncanmmacleod** [comment]
I've had no response from @areeda on this, but approvals from @scottcoughlin2014 and @alurban, so I will merge shortly.

**Pull request merged**
