### PR TITLE
Refactor TimeSeries.coherence to use scipy.signal.coherence

### LINKED ISSUE #1328: Replace mlab.cohere call with scipy.signal.coherence
When coherence was first added to gwpy, it didn't exist in `scipy`, now it does, so we should replace the call to `matplotlib.mlab.cohere` with one to `scipy.signal.coherence`.

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR closes #1328 by reimplementing `TimeSeries.coherence` to call out to `scipy.signal.coherence` rather than `mlab.cohere`.

### CODE REVIEW

**Comment by eagoetz** [comment]
@duncanmmacleod do you have a comparison of coherence values before and after this change just to validate the new version is correct? Thanks!

**Review by areeda — APPROVED** [review]

**Comment by areeda** [comment]
This looks good to me

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod do you have a comparison of coherence values before and after this change just to validate the new version is correct? Thanks!

@eagoetz, the give-away here is that the unit tests have not changed at all, so the reference values have not changed either.

However, for completeness, if you run the `examples/frequencyseries/coherence.py` example script and print the output you get:

<details open>
<summary>GWpy 2.0.4</summary>

```

FrequencySeries([2.39543711e-05, 3.72281754e-05, 5.78254471e-04,
                 ..., 1.25996082e-03, 1.92561118e-04,
                 2.99603517e-05]
                unit: coherence,
                f0: 0.0 Hz,
                df: 0.5 Hz,
                epoch: 1126260017.0,
                name: Coherence between H1:GDS-CALIB_STRAIN and H1:PEM-CS_ACC_PSL_PERISCOPE_X_DQ,
                channel: None)
```

</details>

<details open>
<summary>This PR</summary>

```
FrequencySeries([2.39543711e-05, 3.72281754e-05, 5.78254471e-04,
                 ..., 1.25996082e-03, 1.92561118e-04,
                 2.99603517e-05]
                unit: coherence,
                f0: 0.0 Hz,
                df: 0.5 Hz,
                epoch: 1126260017.0,
                name: Coherence between H1:GDS-CALIB_STRAIN and H1:PEM-CS_ACC_PSL_PERISCOPE_X_DQ,
                channel: None)
```

</details>

i.e. numerically identical.

**Comment by eagoetz** [comment]
@duncanmmacleod Great, thanks for confirming! Also looks good to me and I see you've already merged it. 👍

**Pull request merged**
